name: Run Gex report

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: 
  
 # schedule:
 #   - cron: '16 13,14,16,17,19,20 * * 1-5' 

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  run-gex-job:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install playwright pytest
        python -m playwright install chromium --with-deps

    - name: Run Playwright Script
      env:
        USER_ID: ${{ secrets.TELE_CHAT_ID }}
        USER_SECRET: ${{ secrets.TELE_TOKEN }}
      run: python run.py
